# Generated by Django 4.2.30 on 2026-04-27 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('doctor', 'Bác sĩ'), ('nurse', 'Y tá'), ('receptionist', 'Lễ tân')], max_length=20)),
                ('name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='appointments.vaccinationcenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Lễ tân',
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(blank=True, max_length=200, verbose_name='Chứng chỉ')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Y tá',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Chuyên môn')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='Số chứng chỉ hành nghề')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Bác sĩ',
            },
        ),
    ]
