# Generated by Django 4.2.30 on 2026-05-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='height',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='weight',
        ),
    ]
