# Generated by Django 4.2.30 on 2026-04-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='Nhóm máu')),
                ('allergies', models.TextField(blank=True, verbose_name='Dị ứng')),
                ('chronic_diseases', models.TextField(blank=True, verbose_name='Bệnh mãn tính')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú bác sĩ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'Hồ sơ y tế',
                'verbose_name_plural': 'Hồ sơ y tế',
            },
        ),
    ]
