# Generated by Django 4.2.30 on 2026-05-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Chiều cao (cm)'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cân nặng (kg)'),
        ),
    ]
