# Generated by Django 4.2.30 on 2026-06-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('waiting_exam', 'Đang chờ khám'), ('waiting_injection', 'Đang chờ tiêm'), ('cancelled', 'Đã hủy'), ('paid', 'Đã thanh toán')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
