# Generated by Django 4.2.30 on 2026-04-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('staff', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('vaccine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Tên vaccine')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Nhà sản xuất')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá (VNĐ)')),
                ('required_doses', models.IntegerField(default=1, verbose_name='Số liều cần thiết')),
                ('quantity_available', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('expiry_date', models.DateField(verbose_name='Hạn sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vaccine',
                'verbose_name_plural': 'Vaccine',
            },
        ),
        migrations.CreateModel(
            name='VaccineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng tại trung tâm')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.vaccinationcenter')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccine')),
            ],
            options={
                'verbose_name': 'Kho vaccine',
                'unique_together': {('vaccine', 'center')},
            },
        ),
        migrations.CreateModel(
            name='VaccineAdministration',
            fields=[
                ('vaccine_administration_id', models.AutoField(primary_key=True, serialize=False)),
                ('immunization_hour', models.DateTimeField(verbose_name='Giờ tiêm')),
                ('dose_number', models.IntegerField(default=1, verbose_name='Liều thứ')),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='appointments.appointment')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='staff.doctor')),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injections', to='staff.nurse')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccine')),
            ],
            options={
                'verbose_name': 'Lần tiêm',
                'verbose_name_plural': 'Lịch sử tiêm',
            },
        ),
        migrations.AddField(
            model_name='vaccine',
            name='centers',
            field=models.ManyToManyField(related_name='vaccines', through='vaccines.VaccineStock', to='appointments.vaccinationcenter'),
        ),
    ]
