# Generated by Django 4.2.30 on 2026-04-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vaccines/', verbose_name='Hình ảnh'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='target_disease',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bệnh phòng ngừa'),
        ),
    ]
