# Generated by Django 4.2.30 on 2026-05-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0002_vaccine_description_vaccine_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='quantity_available',
        ),
        migrations.AddField(
            model_name='vaccinestock',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hạn sử dụng'),
        ),
    ]
