# Generated by Django 4.2.30 on 2026-06-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('vaccines', '0003_align_er_diagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineadministration',
            name='post_vaccination_status',
            field=models.TextField(blank=True, verbose_name='Tình trạng sau tiêm'),
        ),
        migrations.AlterField(
            model_name='vaccineadministration',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='staff.doctor'),
        ),
        migrations.AlterField(
            model_name='vaccineadministration',
            name='immunization_hour',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ tiêm'),
        ),
        migrations.AlterField(
            model_name='vaccineadministration',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú bác sĩ'),
        ),
        migrations.AlterField(
            model_name='vaccineadministration',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injections', to='staff.nurse'),
        ),
    ]
