# Generated by Django 4.2.30 on 2026-06-17 08:58

from django.db import migrations, models
import django.db.models.deletion

def migrate_vaccines_and_deduplicate(apps, schema_editor):
    VaccineAdministration = apps.get_model('vaccines', 'VaccineAdministration')
    Sale = apps.get_model('sales', 'Sale')
    
    # 1. Copy old single vaccine FK to Many-to-Many vaccines relation for all rows
    for adm in VaccineAdministration.objects.all():
        if adm.vaccine_id:
            adm.vaccines.add(adm.vaccine_id)
            
    # 2. Find appointments with duplicate administrations
    from django.db.models import Count
    duplicates = (
        VaccineAdministration.objects.values('appointment_id')
        .annotate(count=Count('vaccine_administration_id'))
        .filter(count__gt=1)
    )
    
    for dup in duplicates:
        appt_id = dup['appointment_id']
        adms = list(VaccineAdministration.objects.filter(appointment_id=appt_id).order_by('vaccine_administration_id'))
        primary_adm = adms[0]
        
        # Merge other administrations into the primary one
        for extra_adm in adms[1:]:
            # Copy vaccines to primary
            for vac in extra_adm.vaccines.all():
                primary_adm.vaccines.add(vac)
            
            # Re-link or merge sale
            try:
                extra_sale = Sale.objects.get(vaccine_administration=extra_adm)
                try:
                    primary_sale = Sale.objects.get(vaccine_administration=primary_adm)
                    # Merge sale amount
                    primary_sale.total_amount += extra_sale.total_amount
                    primary_sale.save()
                    extra_sale.delete()
                except Sale.DoesNotExist:
                    extra_sale.vaccine_administration = primary_adm
                    extra_sale.save()
            except Sale.DoesNotExist:
                pass
                
            # Delete the duplicate administration
            extra_adm.delete()

def rollback_vaccines(apps, schema_editor):
    VaccineAdministration = apps.get_model('vaccines', 'VaccineAdministration')
    for adm in VaccineAdministration.objects.all():
        first_vac = adm.vaccines.first()
        if first_vac:
            adm.vaccine = first_vac
            adm.save()

class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_created_by'),
        ('vaccines', '0004_vaccineadministration_post_vaccination_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineadministration',
            name='vaccines',
            field=models.ManyToManyField(related_name='administrations', to='vaccines.vaccine'),
        ),
        migrations.RunPython(
            migrate_vaccines_and_deduplicate,
            reverse_code=rollback_vaccines,
        ),
        migrations.RemoveField(
            model_name='vaccineadministration',
            name='vaccine',
        ),
        migrations.AlterField(
            model_name='vaccineadministration',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administration', to='appointments.appointment'),
        ),
    ]
